### PR TITLE
Help formatter example

### PR DESCRIPTION
**Pull request by Giggitybyte**
I wrote up a little example for the help formatter.
Let me know if it's lacking somewhere 👍

### CODE REVIEW

**Review by VelvetToroyashi — APPROVED** [review]
Looks fine at a glance. Do you have an example of the end result?

**Comment by inftord** [comment]
4.4.1 is latest release btw, but overall LGTM

**Comment by Giggitybyte** [comment]
I have added screenshots of the end result in the README (which i forgor about 💀 )

Command List

Random Help

Timestamp Help

**Comment by Giggitybyte** [comment]
😄

**Pull request merged**
